/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.classroom.jsonc --include-runtime=false classroomWorkerEnv.d.ts` (hash: d782bf2e0a6637f8003155b17e04819b)
interface __BaseEnv_Env {
	COURSE: KVNamespace;
	ADMIN_PASSWORD: string;
	CLASSROOM: DurableObjectNamespace /* Classroom from eddmpython-site */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./classroomWorker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_PASSWORD">> {}
}
