import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { limits } from "./limits.ts";
import { compareTables, sampleTables, textCell, type Table } from "./compare.ts";
import { readWorkbook, reportBytes, tableBytes, checkArchive } from "./workbook.ts";
import * as XLSX from "../../../../site/src/spreadsheet.ts";

const [before, after] = sampleTables();
const keys = ["상품코드"];
const columns = before.headers.slice(1);
const result = compareTables(before, after, keys, columns);
assert.deepEqual([result.changed, result.added, result.removed, result.unchanged], [1, 1, 1, 2]);
assert.deepEqual(result.changes.filter(change => change.status === "변경").map(change => [change.key, change.column, change.before.value, change.after.value, change.beforeRow, change.afterRow]), [["0012", "재고", 30, 24, 2, 3], ["0012", "단가", 18000, 19000, 2, 3]]);
assert.equal(result.changes.length, 10);
assert.equal(compareTables(before, before, keys, columns).changes.length, 0);
const reverse = { ...before, rows: [...before.rows].reverse(), rowNumbers: [...before.rowNumbers].reverse() };
assert.equal(compareTables(before, reverse, keys, columns).changes.length, 0);
const duplicate = structuredClone(before); duplicate.rows[1][0] = textCell("0012");
assert.throws(() => compareTables(duplicate, after, keys, columns), /2행과 3행/);
const empty = structuredClone(before); empty.rows[1][0] = textCell(" ");
assert.throws(() => compareTables(empty, after, keys, columns), /3행.*비어/);
assert.throws(() => compareTables(before, after, [], columns), /기준 열/);
assert.throws(() => compareTables(before, after, keys, []), /값 열/);
assert.throws(() => compareTables(before, after, keys, ["없음"]), /모두 있는/);
const spaces = structuredClone(before); spaces.rows[0][1] = textCell("무선 마우스 ");
assert.equal(compareTables(before, spaces, keys, columns).changed, 1);
assert.equal(compareTables(before, spaces, keys, columns, true).changed, 0);
const typed = structuredClone(before); typed.rows[0][2] = textCell("30");
assert.equal(compareTables(before, typed, keys, columns).changed, 1);
const composite: Table = { headers: ["코드", "창고", "수량"], rows: [[textCell("A / B"), textCell("C"), textCell("1")], [textCell("A"), textCell("B / C"), textCell("2")]], rowNumbers: [2, 3] };
assert.equal(compareTables(composite, composite, ["코드", "창고"], ["수량"]).unchanged, 2);
const compositeChanged = structuredClone(composite); compositeChanged.rows[0][2] = textCell("10"); compositeChanged.rows[1][2] = textCell("20");
assert.equal(new Set(compareTables(composite, compositeChanged, ["코드", "창고"], ["수량"]).changes.map(change => change.key)).size, 2);
const typedKey = structuredClone(before); typedKey.rows[0][0] = { kind: "number", value: 12 };
const replacedKey = compareTables(before, typedKey, keys, columns);
assert.deepEqual([replacedKey.changed, replacedKey.added, replacedKey.removed], [0, 1, 1]);
const trimDuplicate = structuredClone(before); trimDuplicate.rows[1][0] = textCell("0012 ");
assert.throws(() => compareTables(trimDuplicate, after, keys, columns, true), /2행과 3행/);
for (const source of [before, after]) {
  const decoded = readWorkbook(tableBytes(source)).table;
  assert.deepEqual(decoded, source);
  assert.equal(decoded.rows[0][0].kind, "text");
}
const report = XLSX.read(reportBytes(result, { before: "재고_이전.xlsx", after: "재고_이후.xlsx", keys, trim: false }), { type: "array" });
assert.deepEqual(report.SheetNames, ["비교 설정", "변경 내역"]);
assert.equal(report.Sheets["변경 내역"].B2.v, "0012");
assert.equal(report.Sheets["변경 내역"].B2.t, "s");
assert.equal(report.Sheets["변경 내역"].D2.v, 30);
assert.equal(report.Sheets["변경 내역"].E2.v, 24);
const injection = structuredClone(result); injection.changes[0].after = textCell('=HYPERLINK("https://example.invalid","x")');
const safe = XLSX.read(reportBytes(injection, { before: "a", after: "b", keys, trim: false }), { type: "array" });
assert.equal(safe.Sheets["변경 내역"].E2.t, "s");
assert.equal(safe.Sheets["변경 내역"].E2.f, undefined);
assert.throws(() => checkArchive(new TextEncoder().encode("not an xlsx").buffer), /암호가 없는/);
const book = XLSX.read(tableBytes(before), { type: "array" });
book.Sheets["재고"].C2.f = "1+1";
assert.throws(() => readWorkbook(XLSX.write(book, { type: "array", bookType: "xlsx" })), /C2에 수식/);
delete book.Sheets["재고"].C2.f;
book.Sheets["재고"]["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 1 } }];
assert.throws(() => readWorkbook(XLSX.write(book, { type: "array", bookType: "xlsx" })), /병합/);
const workbook = (...sheets: Array<[string, XLSX.WorkSheet]>) => {
  const b = XLSX.utils.book_new();
  for (const [name, sheet] of sheets) XLSX.utils.book_append_sheet(b, sheet, name);
  return XLSX.write(b, { type: "array", bookType: "xlsx", compression: true }) as ArrayBuffer;
};
const laterHeader = XLSX.utils.aoa_to_sheet([["재고 보고서"], [], ["상품코드", "재고"], ["0012", 30], [], ["0013", 15]]);
const sheets = workbook(["안내", XLSX.utils.aoa_to_sheet([["이 시트는 안내입니다"]])], ["실제 재고", laterHeader]);
assert.throws(() => readWorkbook(sheets), /데이터가 없습니다/);
assert.throws(() => readWorkbook(sheets, "실제 재고", 1), /B1의 열 이름/);
assert.deepEqual(readWorkbook(sheets, "실제 재고", 3).table.rowNumbers, [4, 6]);
assert.deepEqual(readWorkbook(sheets, "실제 재고", 3).sheetNames, ["안내", "실제 재고"]);
assert.throws(() => readWorkbook(sheets, "없는 시트"), /시트를 찾지/);
assert.throws(() => readWorkbook(workbook(["재고", XLSX.utils.aoa_to_sheet([["코드", "코드"], ["A", 1]])])), /중복/);
for (const ref of ["A1:A20002", "A1:CW2", "A1:CV3001"]) {
  const huge = XLSX.utils.aoa_to_sheet([["코드"], ["A"]]); huge["!ref"] = ref;
  assert.throws(() => readWorkbook(workbook(["재고", huge])), /20,000행/);
}
const errorSheet = XLSX.utils.aoa_to_sheet([["코드", "값"], ["A", 1]]); errorSheet.B2 = { t: "e", v: 7 };
assert.throws(() => readWorkbook(workbook(["재고", errorSheet])), /B2에 Excel 오류/);
assert.throws(() => checkArchive(new ArrayBuffer(limits.bytes + 1)), /10MB/);
const article = readFileSync(new URL("../index.md", import.meta.url), "utf8");
assert.ok(article.includes(`${limits.bytes / 1024 / 1024}MB까지`));
assert.ok(article.includes(`${limits.rows.toLocaleString("en-US")}행과 ${limits.columns}열, 전체 ${limits.cells.toLocaleString("en-US")}칸`));
console.log("엑셀 비교: 행 재정렬, 추가·삭제·변경, 중복·빈 기준 값, 복합 기준, 공백, 자료형, xlsx 왕복, 보고서, 수식 차단 통과");
