import assert from "node:assert/strict";
import { applyRecipe, boxFrom, extract, inferColumns, makeRegion, mergeCells, numberValue, readRecipe, resetGrid, toRecipe, type PageData, type Word } from "./model.ts";
import { workbookBytes } from "./export.ts";
import * as XLSX from "../../../../site/src/spreadsheet.ts";

const values = [["상품코드", "품목", "수량", "단가", "금액"], ["0012", "무선 마우스", "24", "19,000", "456,000"], ["0013", "키보드", "15", "45,000", "675,000"]];
const words: Word[] = values.flatMap((row, r) => row.map((text, c) => ({ id: `${r}:${c}`, text, x: 0.1 + c * 0.16, y: 0.2 + r * 0.05, width: 0.08, height: 0.018 })));
const page: PageData = { id: "file:1", fileId: "file", fileName: "예제.pdf", number: 1, width: 600, height: 800, words, method: "text" };
const box = { x: 0.08, y: 0.18, width: 0.78, height: 0.15 };
let region = makeRegion(page, box, "table", "표 1");
assert.equal(region.columns.length, 4);
assert.equal(region.rows.length, 2);
let result = extract(page, region);
assert.deepEqual(result.headers, values[0]);
assert.deepEqual(result.data.map(row => row.map(cell => cell.value)), values.slice(1));
assert.equal(result.issues.length, 0);
assert.equal(result.data[0][0].value, "0012");
region = { ...region, numberColumns: [2, 3, 4], checks: { "4": "1,131,000" } };
result = extract(page, region);
assert.equal(result.totals.find(t => t.column === 4)?.matches, true);
assert.equal(result.totals.find(t => t.column === 2)?.actual, 39);
const changed = { ...region, edits: { "1:4": "456,001" } };
const changeResult = extract(page, changed);
assert.equal(changeResult.cells[1][4].original, "456,000");
assert.equal(changeResult.cells[1][4].value, "456,001");
assert.equal(changeResult.cells[1][4].edited, true);
assert.equal(changeResult.totals.find(t => t.column === 4)?.matches, false);
assert.equal(extract(page, { ...region, edits: { "1:4": "1000000000", "2:4": "1" }, checks: { "4": "1000000000" } }).totals.find(t => t.column === 4)?.matches, false);
assert.equal(extract(page, { ...region, edits: { "1:4": "0.1", "2:4": "0.2" }, checks: { "4": "0.3" } }).totals.find(t => t.column === 4)?.matches, true);
assert.equal(extract(page, { ...region, checks: { "4": "1,13" } }).totals.find(t => t.column === 4)?.matches, false);
assert.equal(extract(page, { ...region, omitted: [1] }).data.length, 1);
const lowConfidence = { ...page, method: "ocr" as const, words: words.map((word, i) => i === 5 ? { ...word, confidence: 62 } : word) };
assert.equal(extract(lowConfidence, region).issues.length, 1);
assert.equal(extract(lowConfidence, { ...region, reviewed: ["1:0"] }).issues.length, 0);
const emptyOcr = extract({ ...page, method: "ocr", words: words.filter(word => word.id !== words[5].id) }, region);
assert.ok(emptyOcr.cells[1][0].flags.includes("빈 칸 확인"));
assert.equal(extract(page, { ...region, edits: { "1:2": "24개" } }).totals[0].invalid, 1);
const merged = extract(page, mergeCells(region, { row: 1, column: 0 }, { row: 1, column: 1 }));
assert.equal(merged.cells[1][0].colSpan, 2);
assert.equal(merged.cells[1][1].hidden, true);
assert.equal(merged.cells[1][0].value, "0012 무선 마우스");
assert.deepEqual(resetGrid(changed, {}).edits, {});
for (const [text, expected] of [["1,200", 1200], ["(1,200)", -1200], ["₩ 12.5", 12.5], ["0", 0], ["1,23", null], ["12개", null], ["", null], ["1e3", null], ["9007199254740992", null]] as const) assert.equal(numberValue(text), expected);
const recipe = readRecipe(JSON.stringify(toRecipe([changed])));
assert.equal(JSON.stringify(recipe).includes("456,001"), false);
const applied = applyRecipe(recipe, [page, { ...page, id: "file:2", number: 2 }], (() => { let n = 0; return () => `r${++n}`; })());
assert.equal(applied.length, 2);
assert.notEqual(applied[0].id, applied[1].id);
assert.equal(applied[1].pageId, "file:2");
assert.deepEqual(extract(page, applied[0]).headers, values[0]);
for (const corrupt of ["{}", '{"version":1,"kind":"eddmpython-pdf-table","regions":[null]}', JSON.stringify({ ...recipe, regions: [{ ...recipe.regions[0], columns: [0.6, 0.4] }] }), JSON.stringify({ ...recipe, regions: [{ ...recipe.regions[0], box: { x: 0.8, y: 0, width: 0.9, height: 0.2 } }] })]) assert.throws(() => readRecipe(corrupt));
assert.deepEqual(boxFrom({ x: 1.2, y: 0.9 }, { x: -0.1, y: 0.2 }), { x: 0, y: 0.2, width: 1, height: 0.7 });
assert.deepEqual(inferColumns({ ...page, words: [] }, box), []);
const book = XLSX.read(await workbookBytes([result, changeResult]), { type: "array" });
assert.deepEqual(book.SheetNames, ["통합 표", "원문 근거", "검토 항목"]);
assert.equal(book.Sheets["통합 표"].A2.v, "0012");
assert.equal(book.Sheets["통합 표"].A2.t, "s");
assert.equal(book.Sheets["통합 표"].C2.v, 24);
assert.equal(book.Sheets["통합 표"].C2.t, "n");
assert.equal(book.Sheets["통합 표"].F2.v, "예제.pdf");
assert.equal(book.Sheets["통합 표"].G2.v, 1);
assert.equal(XLSX.utils.sheet_to_json(book.Sheets["통합 표"], { header: 1 }).length, 5);
assert.equal(XLSX.utils.sheet_to_json(book.Sheets["검토 항목"], { header: 1 }).length, 2);
const formulaText = extract(page, { ...region, edits: { "1:1": "=HYPERLINK(\"https://example.com\")" } });
const escaped = XLSX.read(await workbookBytes([formulaText]), { type: "array" });
assert.equal(escaped.Sheets["통합 표"].B2.t, "s");
assert.equal(escaped.Sheets["통합 표"].B2.f, undefined);
const duplicateHeaders = extract(page, { ...region, names: ["코드", "코드", "코드 (2)", "단가", "금액"] });
const duplicateBook = XLSX.read(await workbookBytes([duplicateHeaders]), { type: "array" });
assert.equal(duplicateBook.Sheets["통합 표"].A2.v, "0012");
assert.equal(duplicateBook.Sheets["통합 표"].B2.v, "무선 마우스");
assert.equal(duplicateBook.Sheets["통합 표"].C2.v, 24);
assert.deepEqual(["A1", "B1", "C1"].map(key => duplicateBook.Sheets["통합 표"][key].v), ["코드", "코드 (3)", "코드 (2)"]);
console.log("PDF 표: 경계 추론, 원문 추적, 수정, 병합, 행 제외, OCR 확인, 합계, 설정 검증, 엑셀 형식 검증 완료");
